version: '3.6'
services:
  app:
    build: .
    ports:
      - 8089:8080
    depends_on:
      - db
  db:
    image: mysql:8.0-debian
    container_name: db
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: anime_list
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
