spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME:localhost}:${MYSQL_PORT:3307}/${MYSQL_DBNAME:anime_list}
    username: ${MYSQL_DB_USER:user}
    password: ${MYSQL_DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
